global using CommonBasicLibraries.DatabaseHelpers.EntityInterfaces;
global using CommonBasicLibraries.CollectionClasses;
global using JobApplication.CoreLibrary.Models;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses;
global using aa1 = CommonBasicLibraries.BasicDataSettingsAndProcesses.ApplicationPath;
global using bb1 = CommonBasicLibraries.BasicDataSettingsAndProcesses.BasicDataFunctions;
global using ff1 = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileFunctions;
global using jj1 = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.JsonSerializers.FileHelpers;
global using JobApplication.CoreLibrary.Logic;
global using JobApplication.CoreLibrary.Services;
global using JobApplication.CoreLibrary.ViewModels;
global using Microsoft.AspNetCore.Components;
global using System.Diagnostics.CodeAnalysis;
global using BasicBlazorLibrary.Components.NavigationMenus;
global using System.ComponentModel.DataAnnotations.Schema;
